name: Build Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: demo

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: develop
    
    - name: Checkout Repository
      run: git clone https://github.com/spring-projects/spring-petclinic.git

    - name: Build Docker Image
      run: docker build -t pet-clinic:0.2 .

