name: Testing

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ubuntu:latest

    steps:
    - name: Create Folder
      run: mkdir actions-testing

    - name: Create Folder
      run: sleep 20s