name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: demo

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Test Workflow
      run: echo "GitHub Actions workflow is working"