name: Build Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: demo

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t pet-clinic:0.1 .

