name: Testing

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    container:
      image: public.ecr.aws/m1n8x9y9/techiescamp-repo


    steps:
    - name: Create Folder
      run: mkdir ~/test