name: Testing

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: demo
    container:
      image: ubuntu:latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Create Folder
      run: mkdir ~/test