name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: eks-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 767397914705.dkr.ecr.us-west-2.amazonaws.com/test-image:2.0.0